version: '2'
services:
  build:
    image: untangleinc/mfw:build
    volumes:
      - ./:/home/untangle/openwrt
    command: musl
  build-local-container:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ./:/home/untangle/openwrt
    command: musl

networks:
  default:
    ipam:
       driver: default
       config:
         - subnet: 192.168.123.0/24
