sudo: required

services:
- docker

env:
  COMPOSE_VERSION: 1.17.1

before_install:
- curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- sudo mv docker-compose /usr/local/bin
- docker pull untangleinc/mfw:build

script:
- docker-compose -f mfw/docker-compose.build.yml -p mfw_${device} run build -d x86_64 -l musl -m "-j32 V=s"

notifications:
  email: false
