version: '2'
services:
  mfw:
    build:
      context: .
      dockerfile: Dockerfile.test.mfw
      args:
        - ROOTFS_TARBALL

  test:
    build:
      context: .
      dockerfile: Dockerfile.test.agent
    volumes:
      - ./:/home/mfw/test-agent
