version: '2'
services:
  build:
    image: untangleinc/mfw:build
    environment:
      BUILD_URL:
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
    volumes:
      - ../:/home/mfw/openwrt
  build-local-container:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ../:/home/mfw/openwrt

