version: '2'
services:
  build:
    image: untangleinc/mfw:build
    volumes:
      - ../:/home/mfw/openwrt
  build-local-container:
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - ../:/home/mfw/openwrt

